// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------- //
// picampinos //
// ---------- //

#define picampinos_wrap_target 0
#define picampinos_wrap 15
#define picampinos_pio_version 0

static const uint16_t picampinos_program_instructions[] = {
            //     .wrap_target
    0x20a9, //  0: wait   1 pin, 9
    0x202a, //  1: wait   0 pin, 10
    0x20aa, //  2: wait   1 pin, 10
    0x4008, //  3: in     pins, 8
    0x202a, //  4: wait   0 pin, 10
    0x20aa, //  5: wait   1 pin, 10
    0x4008, //  6: in     pins, 8
    0x202a, //  7: wait   0 pin, 10
    0x20aa, //  8: wait   1 pin, 10
    0x4008, //  9: in     pins, 8
    0x202a, // 10: wait   0 pin, 10
    0x20aa, // 11: wait   1 pin, 10
    0x4008, // 12: in     pins, 8
    0x202a, // 13: wait   0 pin, 10
    0x8000, // 14: push   noblock
    0x00c1, // 15: jmp    pin, 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program picampinos_program = {
    .instructions = picampinos_program_instructions,
    .length = 16,
    .origin = -1,
    .pio_version = picampinos_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config picampinos_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + picampinos_wrap_target, offset + picampinos_wrap);
    return c;
}

static inline void picampinos_program_init( PIO pio, uint32_t sm, uint32_t offset, uint32_t in_base ,uint32_t in_pin_num, uint32_t href_pin, uint32_t pclk_pin)
{
    pio_sm_config c = picampinos_program_get_default_config(offset);
    sm_config_set_set_pins(&c, in_base, in_pin_num);
    sm_config_set_in_pins(&c, in_base);
    sm_config_set_jmp_pin(&c, href_pin);
    // RIGHT shift, autopush DISABLED (manual push)
    sm_config_set_in_shift(&c, true, false, 32); 
    for (uint32_t i = 0; i < in_pin_num; i++)
    {
        pio_gpio_init(pio, in_base + i);
    }
    pio_gpio_init(pio, href_pin);
    pio_gpio_init(pio, pclk_pin);
    pio_sm_set_consecutive_pindirs(pio, sm, in_base, in_pin_num, false);
    pio_sm_set_consecutive_pindirs(pio, sm, href_pin, 1, false);
    pio_sm_set_consecutive_pindirs(pio, sm, pclk_pin, 1, false);
    sm_config_set_clkdiv(&c, 1);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif

