// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------- //
// picampinos //
// ---------- //

#define picampinos_wrap_target 0
#define picampinos_wrap 12
#define picampinos_pio_version 1

// JPEG capture with hardware-gated PCLK (OV5640 register 0x4740=0x25)
// PCLK only toggles when HREF is active (valid data available)
// Manual push every 4 bytes — autopush at 32 is BROKEN on RP2350 (errata RP2350-E6)
//
// Pin mapping (relative to in_base = GPIO 0):
//   pin 0-7:  D[0:7] camera data bus
//   pin 10:   PCLK (pixel clock, hardware-gated under HREF)
//
// ISR: left-shift, NO autopush
// Each push contains 4 bytes packed into a 32-bit word: [B1, B2, B3, B4]
// DMA reads 32-bit words from PIO FIFO
//
// Frame boundaries are detected by VSYNC GPIO interrupt on the CPU, not in PIO.

static const uint16_t picampinos_program_instructions[] = {
            //     .wrap_target
    0x20aa, //  0: wait   1 pin, 10                ; PCLK high — byte 1
    0x4008, //  1: in     pins, 8
    0x202a, //  2: wait   0 pin, 10
    0x20aa, //  3: wait   1 pin, 10                ; PCLK high — byte 2
    0x4008, //  4: in     pins, 8
    0x202a, //  5: wait   0 pin, 10
    0x20aa, //  6: wait   1 pin, 10                ; PCLK high — byte 3
    0x4008, //  7: in     pins, 8
    0x202a, //  8: wait   0 pin, 10
    0x20aa, //  9: wait   1 pin, 10                ; PCLK high — byte 4
    0x4008, // 10: in     pins, 8
    0x202a, // 11: wait   0 pin, 10
    0x8020, // 12: push   noblock                  ; Push 4 packed bytes as one 32-bit word
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program picampinos_program = {
    .instructions = picampinos_program_instructions,
    .length = 13,
    .origin = -1,
    .pio_version = picampinos_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config picampinos_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + picampinos_wrap_target, offset + picampinos_wrap);
    return c;
}

static inline void picampinos_program_init( PIO pio, uint32_t sm, uint32_t offset, uint32_t in_base ,uint32_t in_pin_num )
{
    pio_sm_config c = picampinos_program_get_default_config(offset);
    sm_config_set_set_pins(&c, in_base, in_pin_num);
    sm_config_set_in_pins(&c, in_base);
    sm_config_set_in_shift(&c, false, false, 32);  // left shift, autopush DISABLED (manual push every 4 bytes)
    uint32_t pin_offset;
    for (pin_offset = 0; pin_offset < in_pin_num; pin_offset++)
    {
        pio_gpio_init(pio, in_base + pin_offset);
    }
    pio_sm_set_consecutive_pindirs(pio, sm, in_base, in_pin_num, false);
    sm_config_set_clkdiv(&c, 1);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif
